---
title: Nathan Albrecht Portfolio
timezone: America/New_York
collections:
  books:
    title: Books
    output: false
  posts:
    title: Thoughts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: books
  values:
    Subtitle: 
    Author(s):
    - 
    Edition Number: 
    Amazon Item ID: 
    Goodreads Item ID: 
    Is Favorite: false
    Cover Image:
      Original Image: 
      WebP 400h Image: 
      JPG 400h Image: 
      WebP 200h Image: 
      JPG 200h Image: 
    Notes URL: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/thoughts/:title/"
email: nathanielalbrecht@gmail.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
twitter_username: albrechtnate
github_username: albrechtnate
permalink: "/:title/"
theme: 
plugins:
- jekyll-seo-tag
baseurl: 
